# Generated by Django 3.0.2 on 2020-02-20 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='language',
            field=models.CharField(blank=True, choices=[('ENG', 'English'), ('JA', 'Japanese'), ('CHI', 'Chinese'), ('GER', 'German')], default='ENG', help_text='Language', max_length=10),
        ),
    ]
