# Generated by Django 3.0.2 on 2020-02-27 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_bookinstance_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(help_text='Select a Genre for this book', to='catalog.Genre'),
        ),
    ]
