# Generated by Django 3.0.5 on 2020-04-28 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_bookreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publication_year',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bookreview',
            name='content',
            field=models.TextField(max_length=500),
        ),
    ]
